-- Legacy Source: DW.BERT_AUSD_BP_TA_P_BASISPROD
-- Job: DW.BERT_AUSD_BP_TA_P_BASISPROD
-- BigQuery DDL for the bert_dwh_prod dataset tables

-- Create dataset if it does not exist
CREATE SCHEMA IF NOT EXISTS `project_id.bert_dwh_prod`
OPTIONS(
    location = 'EU'
);

-- Target table: sof_ta_p_basisprod
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_p_basisprod`
(
    CNTRCT_ID STRING,
    EVN STRING,
    TNV_ICCID STRING,
    TNV_MCC STRING,
    TNV_MNC STRING,
    TNV_HLR STRING,
    TNV_SI STRING,
    TNV_ICC_STAT STRING,
    TNV_ICC_VALID TIMESTAMP,
    TC_ICCID STRING,
    TC_MCC STRING,
    TC_MNC STRING,
    TC_HLR STRING,
    TC_SI STRING,
    TC_ICC_STAT STRING,
    TC_ICC_VALID TIMESTAMP,
    TB_ICCID STRING,
    TB_MCC STRING,
    TB_MNC STRING,
    TB_HLR STRING,
    TB_SI STRING,
    TB_ICC_STAT STRING,
    TB_ICC_VALID TIMESTAMP,
    MS1_ICCID STRING,
    MS1_MCC STRING,
    MS1_MNC STRING,
    MS1_HLR STRING,
    MS1_SI STRING,
    MS1_STAT STRING,
    MS1_VALID TIMESTAMP,
    MS2_ICCID STRING,
    MS2_MCC STRING,
    MS2_MNC STRING,
    MS2_HLR STRING,
    MS2_SI STRING,
    MS2_STAT STRING,
    MS2_VALID TIMESTAMP,
    TNV_E_ID STRING,
    TNV_CARD_TYPE_NAME STRING,
    TC_E_ID STRING,
    TC_CARD_TYPE_NAME STRING,
    TB_E_ID STRING,
    TB_CARD_TYPE_NAME STRING,
    MS1_E_ID STRING,
    MS1_CARD_TYPE_NAME STRING,
    MS2_E_ID STRING,
    MS2_CARD_TYPE_NAME STRING,
    TNV_MULTI_SINGLE STRING,
    TC_MULTI_SINGLE STRING,
    TB_MULTI_SINGLE STRING,
    TNV_MSISDN STRING,
    TNV_MS_STAT STRING,
    TNV_MS_VALID TIMESTAMP,
    TNV_DAT_MSISDN STRING,
    TNV_DAT_STAT STRING,
    TNV_DAT_VALID TIMESTAMP,
    TNV_FAX_MSISDN STRING,
    TNV_FAX_STAT STRING,
    TNV_FAX_VALID TIMESTAMP,
    TC_MSISDN STRING,
    TC_MS_STAT STRING,
    TC_MS_VALID TIMESTAMP,
    TC_DAT_MSISDN STRING,
    TC_DAT_STAT STRING,
    TC_DAT_VALID TIMESTAMP,
    TC_FAX_MSISDN STRING,
    TC_FAX_STAT STRING,
    TC_FAX_VALID TIMESTAMP,
    TB_MSISDN STRING,
    TB_MS_STAT STRING,
    TB_MS_VALID TIMESTAMP,
    TB_DAT_MSISDN STRING,
    TB_DAT_STAT STRING,
    TB_DAT_VALID TIMESTAMP,
    TB_FAX_MSISDN STRING,
    TB_FAX_STAT STRING,
    TB_FAX_VALID TIMESTAMP,
    MS1_MSISDN STRING,
    MS1_MS_STAT STRING,
    MS1_MS_VALID TIMESTAMP,
    MS2_MSISDN STRING,
    MS2_MS_STAT STRING,
    MS2_MS_VALID TIMESTAMP,
    DA_MSISDN STRING,
    DA_MS_STAT STRING,
    DA_MS_VALID TIMESTAMP,
    VDA_MSISDN STRING,
    VDA_MS_STAT STRING,
    VDA_MS_VALID TIMESTAMP,
    TK_MSISDN STRING,
    TK_MS_STAT STRING,
    TK_MS_VALID TIMESTAMP,
    BCP_VERTRAG STRING,
    BCP_ICCID STRING,
    BCP_HLR STRING,
    APN STRING,
    BCP_TN_TEL STRING,
    DATA_OPTION_REIN STRING,
    VOICE_OPTION_REIN STRING,
    MIX_OPTION STRING,
    MULTI_OPTION STRING,
    ROAMING_OPTION STRING,
    SONSTIGE_OPTION STRING,
    MS3_ICCID STRING,
    MS3_E_ID STRING,
    MS3_CARD_TYPE_NAME STRING,
    MS3_MCC STRING,
    MS3_MNC STRING,
    MS3_HLR STRING,
    MS3_SI STRING,
    MS3_STAT STRING,
    MS3_VALID TIMESTAMP,
    MS4_ICCID STRING,
    MS4_E_ID STRING,
    MS4_CARD_TYPE_NAME STRING,
    MS4_MCC STRING,
    MS4_MNC STRING,
    MS4_HLR STRING,
    MS4_SI STRING,
    MS4_STAT STRING,
    MS4_VALID TIMESTAMP,
    MS5_ICCID STRING,
    MS5_E_ID STRING,
    MS5_CARD_TYPE_NAME STRING,
    MS5_MCC STRING,
    MS5_MNC STRING,
    MS5_HLR STRING,
    MS5_SI STRING,
    MS5_STAT STRING,
    MS5_VALID TIMESTAMP,
    MS6_ICCID STRING,
    MS6_E_ID STRING,
    MS6_CARD_TYPE_NAME STRING,
    MS6_MCC STRING,
    MS6_MNC STRING,
    MS6_HLR STRING,
    MS6_SI STRING,
    MS6_STAT STRING,
    MS6_VALID TIMESTAMP,
    MS7_ICCID STRING,
    MS7_E_ID STRING,
    MS7_CARD_TYPE_NAME STRING,
    MS7_MCC STRING,
    MS7_MNC STRING,
    MS7_HLR STRING,
    MS7_SI STRING,
    MS7_STAT STRING,
    MS7_VALID TIMESTAMP,
    MS8_ICCID STRING,
    MS8_E_ID STRING,
    MS8_CARD_TYPE_NAME STRING,
    MS8_MCC STRING,
    MS8_MNC STRING,
    MS8_HLR STRING,
    MS8_SI STRING,
    MS8_STAT STRING,
    MS8_VALID TIMESTAMP,
    MS9_ICCID STRING,
    MS9_E_ID STRING,
    MS9_CARD_TYPE_NAME STRING,
    MS9_MCC STRING,
    MS9_MNC STRING,
    MS9_HLR STRING,
    MS9_SI STRING,
    MS9_STAT STRING,
    MS9_VALID TIMESTAMP,
    MS10_ICCID STRING,
    MS10_E_ID STRING,
    MS10_CARD_TYPE_NAME STRING,
    MS10_MCC STRING,
    MS10_MNC STRING,
    MS10_HLR STRING,
    MS10_SI STRING,
    MS10_STAT STRING,
    MS10_VALID TIMESTAMP
);

-- Source table: dwtk_meldungen
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.dwtk_meldungen`
(
    timecreated TIMESTAMP,
    job_kennung STRING
);

-- Source table: sof_ta_cntrct_dist
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_cntrct_dist`
(
    cntrct_id STRING
);

-- Source table: sof_ta_cntrct_evn
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_cntrct_evn`
(
    cntrct_id STRING,
    evn STRING
);

-- Source table: sof_ta_iccid_vertrag
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_iccid_vertrag`
(
    cntrct_id STRING,
    tn_iccid STRING,
    tn_imsi_mcc STRING,
    tn_imsi_mnc STRING,
    tn_imsi_hlr STRING,
    tn_imsi_si STRING,
    tn_status STRING,
    tn_valid_to TIMESTAMP,
    tc_iccid STRING,
    tc_imsi_mcc STRING,
    tc_imsi_mnc STRING,
    tc_imsi_hlr STRING,
    tc_imsi_si STRING,
    tc_status STRING,
    tc_valid_to TIMESTAMP,
    tb_iccid STRING,
    tb_imsi_mcc STRING,
    tb_imsi_mnc STRING,
    tb_imsi_hlr STRING,
    tb_imsi_si STRING,
    tb_status STRING,
    tb_valid_to TIMESTAMP,
    ms1_iccid STRING,
    ms1_imsi_mcc STRING,
    ms1_imsi_mnc STRING,
    ms1_imsi_hlr STRING,
    ms1_imsi_si STRING,
    ms1_status STRING,
    ms1_valid_to TIMESTAMP,
    ms2_iccid STRING,
    ms2_imsi_mcc STRING,
    ms2_imsi_mnc STRING,
    ms2_imsi_hlr STRING,
    ms2_imsi_si STRING,
    ms2_status STRING,
    ms2_valid_to TIMESTAMP,
    tn_e_id STRING,
    tn_card_type_name STRING,
    tc_e_id STRING,
    tc_card_type_name STRING,
    tb_e_id STRING,
    tb_card_type_name STRING,
    ms1_e_id STRING,
    ms1_card_type_name STRING,
    ms2_e_id STRING,
    ms2_card_type_name STRING,
    ms3_iccid STRING,
    ms3_e_id STRING,
    ms3_card_type_name STRING,
    ms3_imsi_mcc STRING,
    ms3_imsi_mnc STRING,
    ms3_imsi_hlr STRING,
    ms3_imsi_si STRING,
    ms3_status STRING,
    ms3_valid_to TIMESTAMP,
    ms4_iccid STRING,
    ms4_e_id STRING,
    ms4_card_type_name STRING,
    ms4_imsi_mcc STRING,
    ms4_imsi_mnc STRING,
    ms4_imsi_hlr STRING,
    ms4_imsi_si STRING,
    ms4_status STRING,
    ms4_valid_to TIMESTAMP,
    ms5_iccid STRING,
    ms5_e_id STRING,
    ms5_card_type_name STRING,
    ms5_imsi_mcc STRING,
    ms5_imsi_mnc STRING,
    ms5_imsi_hlr STRING,
    ms5_imsi_si STRING,
    ms5_status STRING,
    ms5_valid_to TIMESTAMP,
    ms6_iccid STRING,
    ms6_e_id STRING,
    ms6_card_type_name STRING,
    ms6_imsi_mcc STRING,
    ms6_imsi_mnc STRING,
    ms6_imsi_hlr STRING,
    ms6_imsi_si STRING,
    ms6_status STRING,
    ms6_valid_to TIMESTAMP,
    ms7_iccid STRING,
    ms7_e_id STRING,
    ms7_card_type_name STRING,
    ms7_imsi_mcc STRING,
    ms7_imsi_mnc STRING,
    ms7_imsi_hlr STRING,
    ms7_imsi_si STRING,
    ms7_status STRING,
    ms7_valid_to TIMESTAMP,
    ms8_iccid STRING,
    ms8_e_id STRING,
    ms8_card_type_name STRING,
    ms8_imsi_mcc STRING,
    ms8_imsi_mnc STRING,
    ms8_imsi_hlr STRING,
    ms8_imsi_si STRING,
    ms8_status STRING,
    ms8_valid_to TIMESTAMP,
    ms9_iccid STRING,
    ms9_e_id STRING,
    ms9_card_type_name STRING,
    ms9_imsi_mcc STRING,
    ms9_imsi_mnc STRING,
    ms9_imsi_hlr STRING,
    ms9_imsi_si STRING,
    ms9_status STRING,
    ms9_valid_to TIMESTAMP,
    ms10_iccid STRING,
    ms10_e_id STRING,
    ms10_card_type_name STRING,
    ms10_imsi_mcc STRING,
    ms10_imsi_mnc STRING,
    ms10_imsi_hlr STRING,
    ms10_imsi_si STRING,
    ms10_status STRING,
    ms10_valid_to TIMESTAMP
);

-- Source table: sof_ta_rn_vertrag
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_rn_vertrag`
(
    cntrct_id STRING,
    tn_multi_single STRING,
    tc_multi_single STRING,
    tb_multi_single STRING,
    tn_tel_msisdn STRING,
    tn_tel_status STRING,
    tn_tel_valid_to TIMESTAMP,
    tn_dat_msisdn STRING,
    tn_dat_status STRING,
    tn_dat_valid_to TIMESTAMP,
    tn_fax_msisdn STRING,
    tn_fax_status STRING,
    tn_fax_valid_to TIMESTAMP,
    tc_tel_msisdn STRING,
    tc_tel_status STRING,
    tc_tel_valid_to TIMESTAMP,
    tc_dat_msisdn STRING,
    tc_dat_status STRING,
    tc_dat_valid_to TIMESTAMP,
    tc_fax_msisdn STRING,
    tc_fax_status STRING,
    tc_fax_valid_to TIMESTAMP,
    tb_tel_msisdn STRING,
    tb_tel_status STRING,
    tb_tel_valid_to TIMESTAMP,
    tb_dat_msisdn STRING,
    tb_dat_status STRING,
    tb_dat_valid_to TIMESTAMP,
    tb_fax_msisdn STRING,
    tb_fax_status STRING,
    tb_fax_valid_to TIMESTAMP,
    ms_rn_1_msisdn STRING,
    ms_rn_1_status STRING,
    ms_rn_1_valid_to TIMESTAMP,
    ms_rn_2_msisdn STRING,
    ms_rn_2_status STRING,
    ms_rn_2_valid_to TIMESTAMP
);

-- Source table: sof_ta_rn_da_vda_tk
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_rn_da_vda_tk`
(
    cntrct_id STRING,
    da_rn_msisdn STRING,
    da_rn_status STRING,
    da_rn_valid_to TIMESTAMP,
    vda_rn_msisdn STRING,
    vda_rn_status STRING,
    vda_rn_valid_to TIMESTAMP,
    tk_rn_msisdn STRING,
    tk_rn_status STRING,
    tk_rn_valid_to TIMESTAMP
);

-- Source table: sof_ta_tarifoption
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_tarifoption`
(
    cntrct_id STRING,
    data_option_rein STRING,
    voice_option_rein STRING,
    mix_option STRING,
    multi_option STRING,
    roaming_option STRING,
    sonstige_option STRING
);

-- Source table: sof_ta_apn_vertrag
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_apn_vertrag`
(
    cntrct_id STRING,
    apn STRING,
    apn_cntrct STRING
);

-- Source table: sof_ta_bcp_iccid
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_bcp_iccid`
(
    cntrct_id STRING,
    cntrct_id_ref STRING,
    tn_iccid STRING,
    tn_imsi_hlr STRING
);

-- Source table: sof_ta_bcp_msisdn
CREATE TABLE IF NOT EXISTS `project_id.bert_dwh_prod.sof_ta_bcp_msisdn`
(
    cntrct_id STRING,
    cntrct_id_ref STRING,
    tn_tel_msisdn STRING
);