-- BigQuery DDL for exporter_log table
-- Replaces: Log files ($LogDatei) and DWH monitoring (DWMSG_ functions) for job vobs/dw_source/isdwh/exporter/is/bin/r_exis_v2
-- This table stores detailed logs for exporter job runs.

CREATE TABLE IF NOT EXISTS `your_gcp_project_id.your_bigquery_dataset.exporter_log` (
    job_name STRING NOT NULL OPTIONS(description="Unique identifier for the exporter job, e.g., 'r_exis_v2'"),
    run_id STRING NOT NULL OPTIONS(description="Unique identifier for each job run, typically generated by Airflow"),
    log_timestamp TIMESTAMP NOT NULL OPTIONS(description="Timestamp when the log entry was created"),
    log_level STRING NOT NULL OPTIONS(description="Severity level of the log entry (e.g., INFO, WARN, ERROR, DEBUG)"),
    task_id STRING OPTIONS(description="Identifier of the Airflow task that generated the log"),
    message STRING NOT NULL OPTIONS(description="Summary message of the log entry"),
    details JSON OPTIONS(description="JSON object for additional structured log details"),
    PRIMARY KEY (job_name, run_id, log_timestamp) NOT ENFORCED
)
PARTITION BY DATE(log_timestamp)
CLUSTER BY job_name, log_level;