-- BigQuery DDL for raw_dwh.VI_F_NNV_TVD_12_MONATE
-- Replaces source Oracle table DWH$VI_F_NNV_TVD_12_MONATE for job EXIS_SD_APT_NNA_VOIC

CREATE TABLE IF NOT EXISTS `your-gcp-project-id.raw_dwh.VI_F_NNV_TVD_12_MONATE` (
    MONATS_ID INT64 NOT NULL,
    RAHMENVERTRAG STRING,
    DWH_VERTRAG_ID INT64 NOT NULL,
    LEISTUNGSKLASSE_ID INT64 NOT NULL,
    VERBINDUNGEN INT64,
    DAUER_SEK NUMERIC,
    RBETRAG_VBUD_NETTO_CENT NUMERIC,
    _LAST_MODIFIED_TS TIMESTAMP OPTIONS(description="Last modified timestamp for row tracking")
);