"""
DAG Name: d_alis_spaufruf_p0
Description: Migrated orchestration wrapper from Oracle SQL*Plus to Cloud Composer (Apache Airflow).
             Dynamically invokes BigQuery stored procedures replicating the legacy dynamic execution model.
Source File: vobs/dw_source/isdwh/allgemein/is/util/sql/d_alis_spaufruf_p0.sql
"""

from datetime import datetime, timedelta
from typing import Dict, Any
from airflow import DAG
from airflow.models import Variable
from airflow.providers.google.cloud.operators.bigquery import BigQueryExecuteQueryOperator

# =============================================================================
# ENVIRONMENT CONFIGURATIONS (Default fallbacks for local/dev environments)
# =============================================================================
DEFAULT_PROJECT_ID = Variable.get("gcp_project_id", default_var="your_gcp_project_id")
DEFAULT_DATASET_ID = Variable.get("bq_default_dataset", default_var="your_dataset_id")
GCP_CONN_ID = Variable.get("gcp_connection_id", default_var="google_cloud_default")

# Default arguments applied to the DAG and all derived tasks
DEFAULT_ARGS = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2023, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# =============================================================================
# REUSABLE CORE FUNCTIONS
# =============================================================================

def build_stored_procedure_query() -> str:
    """
    Generates a parameterized BigQuery CALL query string.
    Supports dynamic jinja evaluation of runtime variables passed via Airflow DAG run configs.
    
    Legacy Reference:
        Maps directly to the execution parameter `&1` (representing the procedure name and args).
    """
    # Utilizing jinja templating to read from DAG execution configuration (dag_run.conf)
    # with logical fallbacks to default values provided in the task definition.
    return """
    -- Dynamic Stored Procedure call generated by d_alis_spaufruf_p0 orchestration wrapper
    DECLARE bq_proc_project STRING;
    DECLARE bq_proc_dataset STRING;
    DECLARE bq_proc_name STRING;
    
    SET bq_proc_project = COALESCE(
        NULLIF('{{ dag_run.conf.get("project_id", "") }}', ''), 
        '{{ params.project_id }}'
    );
    SET bq_proc_dataset = COALESCE(
        NULLIF('{{ dag_run.conf.get("dataset_id", "") }}', ''), 
        '{{ params.dataset_id }}'
    );
    SET bq_proc_name = COALESCE(
        NULLIF('{{ dag_run.conf.get("procedure_name", "") }}', ''), 
        '{{ params.procedure_name }}'
    );

    -- Running procedure inside BigQuery
    -- Note: Supports multi-parameter strings or raw dynamic procedural syntax
    CALL `{{ params.project_id }}.{{ params.dataset_id }}.{{ params.procedure_name }}`(
        '{{ dag_run.conf.get("procedure_param", params.procedure_param) }}'
    );
    """


def create_bigquery_sp_operator(
    dag: DAG,
    task_id: str = 'execute_stored_procedure_task',
    gcp_conn_id: str = GCP_CONN_ID,
) -> BigQueryExecuteQueryOperator:
    """
    Modular builder function that constructs and returns the BigQueryExecuteQueryOperator.
    
    :param dag: The parent DAG instance.
    :param task_id: Identifier of the generated task.
    :param gcp_conn_id: The Airflow Connection ID for Google Cloud Services.
    :return: A fully configured BigQueryExecuteQueryOperator instance.
    """
    sql_query = build_stored_procedure_query()
    
    # Base parameter configurations (used if not overridden by dynamic dag_run configs)
    default_parameters: Dict[str, Any] = {
        'project_id': DEFAULT_PROJECT_ID,
        'dataset_id': DEFAULT_DATASET_ID,
        'procedure_name': 'your_default_stored_procedure',
        'procedure_param': 'your_default_parameter_value'
    }

    return BigQueryExecuteQueryOperator(
        task_id=task_id,
        sql=sql_query,
        gcp_conn_id=gcp_conn_id,
        use_legacy_sql=False,
        params=default_parameters,
        write_disposition='WRITE_APPEND', # Safe default for potential DML procedures
        create_disposition='CREATE_IF_NEEDED',
        dag=dag
    )


# =============================================================================
# DAG DEFINITION
# =============================================================================

# Instantiating the execution DAG. Manual/API invocation (schedule=None) mirrors 
# the legacy behavior of command-line executed wrapper scripts.
with DAG(
    dag_id='d_al_is_spaufruf_p0_dag',
    default_args=DEFAULT_ARGS,
    description='Modular Airflow DAG executing BigQuery Stored Procedures replicating legacy SQL*Plus wrapper behavior',
    schedule_interval=None,
    catchup=False,
    tags=['migration', 'dwh', 'dynamic_execution'],
) as dynamic_sp_dag:

    # 1. Instantiate the modular execution operator
    execute_sp_task = create_bigquery_sp_operator(dag=dynamic_sp_dag)

    # 2. Structural Lineage Node (Represented as a single execute block)
    # Additional pre-execution checks (migrated from d_alis_init.sql checks) can be linked here.
    execute_sp_task