"""
DAG: dw_bert_ausd_bp_ta_cntrct_evn
Autogenerated from Legacy UC4 and Shell wrappers for Bert EVN Provisioning.
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.models import Variable
from airflow.providers.google.cloud.operators.bigquery import BigQueryExecuteQueryOperator
from airflow.operators.empty import EmptyOperator

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "start_date": datetime(2026, 4, 21),
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="dw_bert_ausd_bp_ta_cntrct_evn",
    default_args=default_args,
    description="Truncate and reload contract EVN data by aggregating event indicators from the base product event table.",
    schedule_interval="0 4 * * *",  # Scheduled daily at 04:00 AM
    catchup=False,
    tags=["bigquery", "dw", "bert", "basisprodukt", "evn"],
    template_searchpath=["/home/airflow/gcs/dags/sql", "/opt/airflow/dags/sql", "sql/"],
) as dag:

    start_task = EmptyOperator(task_id="start")

    # Single BigQuery execution task referencing standard SQL file with templated parameters
    execute_sql_task = BigQueryExecuteQueryOperator(
        task_id="process_bert_basisprodukte_evn",
        sql="d_ausd_bp_ta_cntrct_evn.sql",
        use_legacy_sql=False,
        location="EU",
    )

    end_task = EmptyOperator(task_id="end")

    start_task >> execute_sql_task >> end_task