# Airflow DAG for DW.BERT_AUSD_BP_TA_APN_VERTRAG
# Legacy source: vobs/dw_source/isdwh/uc4_prod_exports/.../DW.BERT_AUSD_BP_TA_APN_VERTRAG.xml
# This DAG orchestrates the execution of the APN contract processing job.

from __future__ import annotations

import pendulum
from airflow.models.dag import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryOperator

# Import the Python wrapper script's main function
# Assumes k_ausd_bp_ta_apn_vertrag_wrapper.py is in the same DAGs folder or importable via PYTHONPATH
from k_ausd_bp_ta_apn_vertrag_wrapper import main as ksh_wrapper_main

with DAG(
    dag_id="dw_bert_ausd_bp_ta_apn_vertrag",
    start_date=pendulum.datetime(2023, 1, 1, tz="UTC"),
    schedule=None,
    catchup=False,
    tags=["dw", "bert", "apn", "vertrag"],
    doc_md="""
    ### DW.BERT_AUSD_BP_TA_APN_VERTRAG Airflow DAG

    This DAG replaces the legacy UC4 job `DW.BERT_AUSD_BP_TA_APN_VERTRAG`.
    It orchestrates the preparation of instantiated base products, processing
    Access Point Name (APN) and contract reference data.

    **Data Flow:**
    1.  `execute_control_script`: A PythonOperator that mimics the KornShell script's
        logic (parameter parsing, date validation). It loads the BigQuery SQL
        transformation and pushes it to XComs.
    2.  `execute_bq_sql`: A BigQueryOperator that pulls the SQL from XComs and
        executes it against BigQuery.
    """,
) as dag:
    # Task to execute the Python wrapper script (replaces KornShell logic)
    execute_control_script = PythonOperator(
        task_id="execute_control_script",
        python_callable=ksh_wrapper_main,
        op_kwargs={
            "job_kennung": "AUSD_BP_TA_APN_VERTRAG",
            "stichtag": "{{ ds_nodash }}",  # Airflow macro for current date as YYYYMMDD
            "eintragsnr": 1,
            "wiederanlaufwert": 0,
        },
        provide_context=True,  # Enable access to XComs
    )

    # Task to execute the BigQuery SQL generated by the Python script
    execute_bq_sql = BigQueryOperator(
        task_id="execute_bq_sql",
        sql="{{ task_instance.xcom_pull(task_ids='execute_control_script', key='bq_sql_to_execute') }}",
        use_legacy_sql=False,  # Use BigQuery Standard SQL
        bigquery_conn_id="google_cloud_default",  # Assumes a BigQuery connection is configured
    )

    # Define task dependencies
    execute_control_script >> execute_bq_sql