"""
Airflow DAG for EXIS_SD_APT_BESTANDS.

This DAG orchestrates the export of stock data,
migrated from a UC4 job and Oracle PL/SQL.
It extracts data from BigQuery, processes it, adds a custom footer,
and then transfers it to an SFTP server.
"""

from __future__ import annotations

import datetime
import gzip
import io
import tempfile

from airflow.models.dag import DAG
from airflow.operators.dummy import DummyOperator
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
from airflow.providers.google.cloud.transfers.bigquery_to_gcs import BigQueryToCloudStorageOperator
from airflow.providers.google.cloud.hooks.gcs import GCSHook
from airflow.providers.sftp.hooks.sftp import SFTPHook
from airflow.utils.dates import days_ago

# --- Configuration ---
GCP_PROJECT_ID = "your_project"  # Replace with your GCP project ID
BIGQUERY_DATASET_ID = "your_dataset"  # Replace with your BigQuery dataset ID
GCS_BUCKET_NAME = "your-gcs-bucket-name"  # Replace with your GCS bucket name
SFTP_CONN_ID = "sftp_default"  # Airflow connection ID for SFTP
SFTP_REMOTE_PATH = "/path/to/sftp/target/"  # Remote directory on SFTP server

DAG_ID = "dw_dwh_exis_sd_apt_bestands"
BIGQUERY_TEMP_TABLE_PREFIX = "temp_exis_sd_apt_bestands"
GCS_EXPORT_FILENAME_PREFIX = "DWHM_APT_BESTANDSREPORT_"
GCS_EXPORT_FILENAME_SUFFIX = ".csv.gz"

# --- Helper Functions for PythonOperators ---

def _add_csv_footer_to_gcs_file(
    gcs_bucket: str,
    gcs_object_path_xcom_key: str,
    sftp_target_filename_prefix: str,
    sftp_target_filename_suffix: str,
    **kwargs,
):
    """
    Downloads a gzipped CSV from GCS, adds a custom footer line as per the nawk logic,
    re-compresses, and uploads it back to GCS.
    The footer includes the record count and dynamic dates.
    """
    ti = kwargs['ti']
    # XCom-pulled value is a list of URIs, take the first one
    gcs_uri = ti.xcom_pull(task_ids=gcs_object_path_xcom_key, key='return_value')[0]
    gcs_object_name = gcs_uri.split(f"gs://{gcs_bucket}/")[1]

    execution_date_nodash = kwargs['ds_nodash']  # YYYYMMDD
    # The design refers to "DESTINATION_FILE", which implies the final file name that goes to SFTP.
    # This includes the timestamp generated by BQ export.
    destination_file_name_for_footer = f"{sftp_target_filename_prefix}{kwargs['ts_nodash']}{sftp_target_filename_suffix}"

    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')

    # Download gzipped content
    gzipped_content = gcs_hook.download(bucket_name=gcs_bucket, object_name=gcs_object_name)

    # Decompress and read lines
    decompressed_content = gzip.decompress(gzipped_content).decode('utf-8')
    lines = decompressed_content.splitlines()

    # Count data lines. BigQueryToCloudStorageOperator with print_header=False
    # exports data rows only, so len(lines) is the record count.
    data_record_count = len(lines)

    # Construct footer string: "X|<DESTINATION_FILE>|<FROM YYYYMMDD>|" NR "|V_S_Bestandsreport|<SYSDATE YYYYMMDD>"
    footer_string = (
        f"X|{destination_file_name_for_footer}|{execution_date_nodash}|"
        f"{data_record_count}|V_S_Bestandsreport|{execution_date_nodash}"
    )

    # Append footer
    lines.append(footer_string)
    final_content = "\n".join(lines) + "\n"  # Ensure trailing newline for CSV consistency

    # Re-compress and upload, overwriting the original file in GCS
    recompressed_content = gzip.compress(final_content.encode('utf-8'))
    gcs_hook.upload(
        bucket_name=gcs_bucket,
        object_name=gcs_object_name,
        data=recompressed_content,
        mime_type='application/gzip',
        gzip=False  # Data is already gzipped
    )
    kwargs['log'].info(f"Added footer to {gcs_object_name} and re-uploaded to GCS.")


def _sftp_file_from_gcs(
    gcs_bucket: str,
    gcs_object_path_xcom_key: str,
    sftp_conn_id: str,
    sftp_remote_path: str,
    **kwargs,
):
    """
    Downloads the processed file from GCS and uploads it to the SFTP target.
    """
    ti = kwargs['ti']
    # XCom-pulled value is a list of URIs, take the first one
    gcs_uri = ti.xcom_pull(task_ids=gcs_object_path_xcom_key, key='return_value')[0]
    gcs_object_name = gcs_uri.split(f"gs://{gcs_bucket}/")[1]

    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')
    sftp_hook = SFTPHook(sftp_conn_id=sftp_conn_id)

    # Use a temporary file for download/upload to handle potentially large files
    with tempfile.NamedTemporaryFile("wb", delete=True) as temp_file:
        kwargs['log'].info(f"Downloading {gcs_object_name} from GCS to local temp file.")
        gcs_hook.download(bucket_name=gcs_bucket, object_name=gcs_object_name, filename=temp_file.name)
        temp_file.flush()  # Ensure all data is written to disk

        remote_full_path = f"{sftp_remote_path}{gcs_object_name.split('/')[-1]}"
        kwargs['log'].info(f"Uploading local temp file to SFTP: {remote_full_path}")
        sftp_hook.store_file(remote_full_path, temp_file.name)

    kwargs['log'].info(f"Successfully transferred {gcs_object_name} to SFTP {remote_full_path}.")


# --- Airflow DAG Definition ---

with DAG(
    dag_id=DAG_ID,
    start_date=days_ago(1),  # Set a historical start date for backfilling if needed
    schedule_interval=None,  # Not derivable from UC4 XML, set to None for manual/event-driven
    catchup=False,
    tags=["exis", "sd", "apt", "bestands", "bigquery", "gcs", "sftp"],
    default_args={
        "owner": "airflow",
        "depends_on_past": False,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 0,  # As per UC4 analysis, default retries to 0
    },
) as dag:
    start_task = DummyOperator(
        task_id="start",
    )

    # 1. Execute BigQuery SQL and store results in a temporary table
    # This uses BigQueryInsertJobOperator to run a query and write to a destination table.
    # The SQL is read from an external file using Jinja templating.
    bigquery_temp_table_name = f"{GCP_PROJECT_ID}.{BIGQUERY_DATASET_ID}.{BIGQUERY_TEMP_TABLE_PREFIX}_{{{{ ts_nodash }}}}"
    run_bestands_query_to_temp_table = BigQueryInsertJobOperator(
        task_id="run_bestands_query_to_temp_table",
        configuration={
            "query": {
                "query": "{% include 'sql/d_exis_apt_bestandsdaten.bqsql' %}",
                "useLegacySql": False,
                "destinationTable": {
                    "projectId": GCP_PROJECT_ID,
                    "datasetId": BIGQUERY_DATASET_ID,
                    "tableId": f"{BIGQUERY_TEMP_TABLE_PREFIX}_{{{{ ts_nodash }}}}"
                },
                "createDisposition": "CREATE_IF_NEEDED",
                "writeDisposition": "WRITE_TRUNCATE",
            }
        },
        gcp_conn_id='google_cloud_default',
    )

    # 2. Export the temporary BigQuery table to GCS as a compressed CSV file
    # The filename includes a timestamp for uniqueness and matching the source specification.
    gcs_output_uri = f"gs://{GCS_BUCKET_NAME}/{GCS_EXPORT_FILENAME_PREFIX}{{{{ ts_nodash }}}}{GCS_EXPORT_FILENAME_SUFFIX}"
    export_temp_table_to_gcs = BigQueryToCloudStorageOperator(
        task_id="export_temp_table_to_gcs",
        source_project_dataset_table=bigquery_temp_table_name,
        destination_cloud_storage_uris=[gcs_output_uri],
        compression="GZIP",
        export_format="CSV",
        field_delimiter=",",
        print_header=False,  # Important: Do not print header, footer will be added manually
        gcp_conn_id='google_cloud_default',
    )

    # 3. Add the custom footer line to the GCS file
    # This PythonOperator calls a helper function to download, modify, and re-upload the file.
    add_csv_footer = PythonOperator(
        task_id="add_csv_footer_to_gcs_file",
        python_callable=_add_csv_footer_to_gcs_file,
        op_kwargs={
            "gcs_bucket": GCS_BUCKET_NAME,
            "gcs_object_path_xcom_key": "export_temp_table_to_gcs",
            "sftp_target_filename_prefix": GCS_EXPORT_FILENAME_PREFIX,
            "sftp_target_filename_suffix": GCS_EXPORT_FILENAME_SUFFIX,
        },
        provide_context=True, # Allows access to kwargs like ds_nodash, ts_nodash etc.
    )

    # 4. Transfer the file from GCS to the external SFTP target
    transfer_file_to_sftp = PythonOperator(
        task_id="sftp_file_to_external_target",
        python_callable=_sftp_file_from_gcs,
        op_kwargs={
            "gcs_bucket": GCS_BUCKET_NAME,
            "gcs_object_path_xcom_key": "export_temp_table_to_gcs",
            "sftp_conn_id": SFTP_CONN_ID,
            "sftp_remote_path": SFTP_REMOTE_PATH,
        },
        provide_context=True,
    )

    end_task = DummyOperator(
        task_id="end",
    )

    start_task >> run_bestands_query_to_temp_table >> export_temp_table_to_gcs >> add_csv_footer >> transfer_file_to_sftp >> end_task