SELECT
  NNA.MONATS_ID,	
  NNA.RAHMENVERTRAG,	
  NNA.MSISDN,	
  VER.KUNDENKONTO, 
  VER.T_MOBILE_KUNDENNUMMER,
  TAR.TARIF_ID,
  CONCAT(COALESCE(TAR.MP_MARKTPRODUKT_BEZ, ''), ',', COALESCE(TAR.MP_EG_JN_BEZ, ''), ',', COALESCE(TAR.MP_GENERATION_BEZ, '')) AS TARIF,
  NNA.AUSLAND_FLAG,
  ROUND(NNA.GESAMTVOLUMEN_BYTE/1024/1024, 0) AS GESAMTVOLUMEN_BYTE,
  ROUND(NNA.RBETRAG_VBUD_NETTO_CENT_VOL/100, 2) AS RBETRAG_VBUD_NETTO_EURO_VOL,
  TAR.MP_EG_JN_ID,
  TAR.MP_EG_JN_BEZ,
  TAR.MP_GENERATION_ID,
  TAR.MP_GENERATION_BEZ
FROM 
  (
    SELECT 
      TRF.DWH_TARIF_ID, 
      TRF.TARIF_ID,  
      D.MP_MARKTPRODUKT_BEZ, 
      D.MP_EG_JN_BEZ, 
      D.MP_GENERATION_BEZ, 
      TRF.GUELTIG_BIS,
      D.MP_EG_JN_ID,
      D.MP_GENERATION_ID		
    FROM 
      `prod_dwh_raw_dataset.DWH$VI_L_MAP_FA_TARIF` TRF
    INNER JOIN 
      `prod_dwh_raw_dataset.BL_D_TARIF` D
    ON 
      TRF.TARIF_ID = D.TARIF_ID
  ) TAR
INNER JOIN 
  `prod_dwh_raw_dataset.DWH$VI_C_VERTRAG` VER
ON 
  TAR.DWH_TARIF_ID = VER.DWH_TARIF_ID
INNER JOIN 
  `prod_dwh_raw_dataset.DWH$TA_F_NNV_GPRS` NNA
ON 
  VER.DWH_VERTRAG_ID = NNA.DWH_VERTRAG_ID
WHERE 
  NNA.RAHMENVERTRAG IS NOT NULL 
  AND NNA.MONATS_ID = @MONAT_ID
  AND TAR.GUELTIG_BIS = DATE '4712-12-31';