SELECT
  RPT.RAHMENVERTRAG_ID,
  RPT.SV_ID AS TARIF_ID,
  RPT.PARTNER_ID_CARMEN AS T_MOBILE_KUNDENNUMMER,
  RPT.KUNDENKONTO,
  RPT.MSISDN,
  RPT.GEPLANT_KUEND,
  RPT.BINDEFRIST,
  FORMAT_DATE('%d.%m.%Y', CAST(RPT.VERTRAGSBEGINN AS DATE)) AS VERTRAGSBEGINN,
  RPT.VERTRAGSBINDUNG,
  RPT.DWH_TARIFGR_TEXT,
  CAST(STRING_AGG(CAST(A.BPR_ID AS STRING), ',' ORDER BY A.BPR_ID) AS STRING) AS BASISPRODUKTE
FROM
  `prod_dwh_raw_dataset.RPT$TA_S_D1_VERTRAG` RPT
INNER JOIN (
  SELECT
    BPR.CNTRCT_ID,
    BPR.BPR_ID
  FROM
    `prod_dwh_raw_dataset.SOF$TA_BPR_OPTIONEN` BPR
  INNER JOIN
    `prod_dwh_raw_dataset.SOF$VI_L_OPTIONZUORDNUNG` OPT
  ON
    BPR.BPR_ID = OPT.OPTION_ID
) A
ON
  RPT.VERTRAG_ID_CARMEN = A.CNTRCT_ID
GROUP BY
  RPT.RAHMENVERTRAG_ID,
  RPT.VERTRAG_ID_CARMEN,
  RPT.SV_ID,
  RPT.PARTNER_ID_CARMEN,
  RPT.KUNDENKONTO,
  RPT.MSISDN,
  RPT.GEPLANT_KUEND,
  RPT.BINDEFRIST,
  RPT.VERTRAGSBEGINN,
  RPT.VERTRAGSBINDUNG,
  RPT.DWH_TARIFGR_TEXT,
  RPT.VERTRAGSSTATUS
ORDER BY
  RPT.VERTRAG_ID_CARMEN;