SELECT
  RAHMENVERTRAG_ID,
  CNTRCT_TEMPLATE_ID AS TARIF_ID,
  DWH_TARIFGR_TEXT,
  RABATTIERTE_RECH_POS,
  DISC_INVOICE_ITEM_ID AS RABATTIERTE_RECH_POS_ID,
  RABATTHOEHE,
  CAST(STRING_AGG(CAST(BPR_ID AS STRING), ',' ORDER BY BPR_ID) AS STRING) AS BASISPRODUKTE
FROM (
  SELECT DISTINCT 
    RPT.RAHMENVERTRAG_ID,
    RPT.DWH_TARIFGR_TEXT,
    DISC.CNTRCT_TEMPLATE_ID,
    DISC.RABATTIERTE_RECH_POS,
    DISC.DISC_INVOICE_ITEM_ID,
    DISC.RABATTHOEHE,        
    BPR.BPR_ID
  FROM 
    `prod_dwh_raw_dataset.RPT$TA_S_D1_VERTRAG` RPT
  INNER JOIN 
    `prod_dwh_raw_dataset.RPT$TA_S_D1_DISCOUNT_RR` DISC 
  ON 
    RPT.RAHMENVERTRAG_ID = DISC.CONTRACT_NUMBER 
    AND RPT.SV_ID = DISC.CNTRCT_TEMPLATE_ID 
  INNER JOIN 
    `prod_dwh_raw_dataset.SOF$TA_BPR_OPTIONEN` BPR
  ON 
    RPT.VERTRAG_ID_CARMEN = BPR.CNTRCT_ID
  INNER JOIN 
    `prod_dwh_raw_dataset.SOF$VI_L_OPTIONZUORDNUNG` OPT 
  ON 
    BPR.BPR_ID = OPT.OPTION_ID
)
GROUP BY 
  RAHMENVERTRAG_ID,
  CNTRCT_TEMPLATE_ID,
  DWH_TARIFGR_TEXT,
  RABATTIERTE_RECH_POS,
  DISC_INVOICE_ITEM_ID,
  RABATTHOEHE;