-- BigQuery DDL for Oracle Source Tables
-- Legacy Source: EXIS_SD_APT_RABATT
-- Job: EXIS_SD_APT_RABATT

-- Placeholder DDL. Actual schemas should be derived from source Oracle systems.
-- Assumes these tables will be replicated into a BigQuery dataset named 'ORACLE_DATA'.

CREATE SCHEMA IF NOT EXISTS `PROJECT_ID.ORACLE_DATA`;

CREATE OR REPLACE TABLE `PROJECT_ID.ORACLE_DATA.RPT_TA_S_D1_VERTRAG`
(
    RAHMENVERTRAG_ID STRING,
    DWH_TARIFGR_TEXT STRING,
    SV_ID STRING,
    VERTRAG_ID_CARMEN STRING
);

CREATE OR REPLACE TABLE `PROJECT_ID.ORACLE_DATA.RPT_TA_S_D1_DISCOUNT_RR`
(
    CNTRCT_TEMPLATE_ID STRING,
    RABATTIERTE_RECH_POS STRING,
    DISC_INVOICE_ITEM_ID STRING,
    RABATTHOEHE FLOAT64,
    CONTRACT_NUMBER STRING
);

CREATE OR REPLACE TABLE `PROJECT_ID.ORACLE_DATA.SOF_TA_BPR_OPTIONEN`
(
    BPR_ID STRING,
    CNTRCT_ID STRING
);

CREATE OR REPLACE TABLE `PROJECT_ID.ORACLE_DATA.SOF_VI_L_OPTIONZUORDNUNG`
(
    OPTION_ID STRING
);