-- DDL for job_log table
-- Replaces logging functionality from vobs/dw_source/isrpt/isbert/SQL/aktuell/aufbereitung/bin/r_ausd_bp_ta_bpr_opt_text.ksh
-- and associated DWMSG functions.

CREATE TABLE IF NOT EXISTS `project.dataset.job_log` (
    log_time TIMESTAMP NOT NULL OPTIONS(description="Timestamp of the log entry"),
    log_level STRING NOT NULL OPTIONS(description="Severity level of the log (e.g., 'INFO', 'WARNING', 'ERROR')"),
    job_name STRING NOT NULL OPTIONS(description="Name of the job or stored procedure generating the log"),
    message STRING NOT NULL OPTIONS(description="Log message content")
)
OPTIONS(
    description="Detailed log table for capturing messages generated by BigQuery jobs and stored procedures."
);