-- Legacy Source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_rabattdaten.sql
-- Job: DW.BERT_ABLAUFSTEUERUNG
-- Converted to BigQuery SQL

CREATE OR REPLACE TABLE `{{ var.value.TARGET_BQ_PROJECT }}.{{ var.value.TARGET_BQ_DATASET }}.bert_rabattdaten`
AS
SELECT
  RAHMENVERTRAG_ID,
  CNTRCT_TEMPLATE_ID AS TARIF_ID,
  DWH_TARIFGR_TEXT,
  RABATTIERTE_RECH_POS,
  DISC_INVOICE_ITEM_ID AS RABATTIERTE_RECH_POS_ID,
  RABATTHOEHE,
  STRING_AGG(BPR_ID, ',' ORDER BY BPR_ID) AS BASISPRODUKTE
FROM
  (
    SELECT
      DISTINCT
      RPT.RAHMENVERTRAG_ID,
      RPT.DWH_TARIFGR_TEXT,
      DISC.CNTRCT_TEMPLATE_ID,
      DISC.RABATTIERTE_RECH_POS,
      DISC.DISC_INVOICE_ITEM_ID,
      DISC.RABATTHOEHE,
      BPR.BPR_ID
    FROM
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.RPT_TA_S_D1_VERTRAG` RPT
    JOIN
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.RPT_TA_S_D1_DISCOUNT_RR` DISC
    ON
      RPT.RAHMENVERTRAG_ID = DISC.CONTRACT_NUMBER
      AND RPT.SV_ID = DISC.CNTRCT_TEMPLATE_ID
    JOIN
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.SOF_TA_BPR_OPTIONEN` BPR
    ON
      RPT.VERTRAG_ID_CARMEN = BPR.CNTRCT_ID
    JOIN
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.SOF_VI_L_OPTIONZUORDNUNG` OPT
    ON
      BPR.BPR_ID = OPT.OPTION_ID
  )
GROUP BY
  RAHMENVERTRAG_ID,
  CNTRCT_TEMPLATE_ID,
  DWH_TARIFGR_TEXT,
  RABATTIERTE_RECH_POS,
  DISC_INVOICE_ITEM_ID,
  RABATTHOEHE;