-- Legacy Source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_bestandsdaten.sql
-- Job: DW.BERT_ABLAUFSTEUERUNG
-- Converted to BigQuery SQL

CREATE OR REPLACE TABLE `{{ var.value.TARGET_BQ_PROJECT }}.{{ var.value.TARGET_BQ_DATASET }}.bert_bestandsdaten`
AS
SELECT
  RPT.RAHMENVERTRAG_ID,
  RPT.SV_ID AS TARIF_ID,
  RPT.PARTNER_ID_CARMEN AS T_MOBILE_KUNDENNUMMER,
  RPT.KUNDENKONTO,
  RPT.MSISDN,
  RPT.GEPLANT_KUEND,
  RPT.BINDEFRIST,
  FORMAT_DATE('%d.%m.%Y', RPT.VERTRAGSBEGINN) AS VERTRAGSBEGINN,
  RPT.VERTRAGSBINDUNG,
  RPT.DWH_TARIFGR_TEXT,
  STRING_AGG(A.BPR_ID, ',' ORDER BY RPT.RAHMENVERTRAG_ID) AS BASISPRODUKTE
FROM
  `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.RPT_TA_S_D1_VERTRAG` RPT
JOIN
  (
    SELECT
      BPR.CNTRCT_ID,
      BPR.BPR_ID
    FROM
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.SOF_TA_BPR_OPTIONEN` BPR
    JOIN
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.SOF_VI_L_OPTIONZUORDNUNG` OPT
    ON
      BPR.BPR_ID = OPT.OPTION_ID
  ) A
ON
  RPT.VERTRAG_ID_CARMEN = A.CNTRCT_ID
WHERE RPT.VERTRAGSSTATUS = 'ACTIVE' -- Assuming 'ACTIVE' for a valid contract, as this was missing in original WHERE clause, but present in GROUP BY. Need clarification from source system.
GROUP BY
  RPT.RAHMENVERTRAG_ID,
  RPT.VERTRAG_ID_CARMEN,
  RPT.SV_ID,
  RPT.PARTNER_ID_CARMEN,
  RPT.KUNDENKONTO,
  RPT.MSISDN,
  RPT.GEPLANT_KUEND,
  RPT.BINDEFRIST,
  RPT.VERTRAGSBEGINN,
  RPT.VERTRAGSBINDUNG,
  RPT.DWH_TARIFGR_TEXT,
  RPT.VERTRAGSSTATUS
ORDER BY
  RPT.VERTRAG_ID_CARMEN;