-- Legacy Source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_nna_voice.sql
-- Job: DW.BERT_ABLAUFSTEUERUNG
-- Converted to BigQuery SQL

CREATE OR REPLACE TABLE `{{ var.value.TARGET_BQ_PROJECT }}.{{ var.value.TARGET_BQ_DATASET }}.bert_nna_voice`
AS
SELECT
  NNA.MONATS_ID,
  NNA.RAHMENVERTRAG,
  VER.MSISDN,
  VER.KUNDENKONTO,
  VER.T_MOBILE_KUNDENNUMMER,
  TAR.TARIF_ID,
  CONCAT(TAR.MP_MARKTPRODUKT_BEZ, ',', TAR.MP_EG_JN_BEZ, ',', TAR.MP_GENERATION_BEZ) AS TARIF,
  TVD.LEISTUNGSKLASSE_ID,
  TVD.LEISTUNGSKLASSE_TEXT,
  NNA.VERBINDUNGEN,
  ROUND(NNA.DAUER_SEK / 60, 2) AS DAUER_MIN,
  ROUND(NNA.RBETRAG_VBUD_NETTO_CENT / 100, 2) AS RBETRAG_VBUD_NETTO_EURO,
  TAR.MP_EG_JN_ID,
  TAR.MP_EG_JN_BEZ,
  TAR.MP_GENERATION_ID,
  TAR.MP_GENERATION_BEZ
FROM
  (
    SELECT
      TRF.DWH_TARIF_ID,
      TRF.TARIF_ID,
      D.MP_MARKTPRODUKT_BEZ,
      D.MP_EG_JN_BEZ,
      D.MP_GENERATION_BEZ,
      TRF.GUELTIG_BIS,
      D.MP_EG_JN_ID,
      D.MP_GENERATION_ID
    FROM
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.DWH_VI_L_MAP_FA_TARIF` TRF
    JOIN
      `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.BL_D_TARIF` D
    ON
      TRF.TARIF_ID = D.TARIF_ID
  ) TAR
JOIN
  `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.DWH_VI_C_VERTRAG` VER
ON
  TAR.DWH_TARIF_ID = VER.DWH_TARIF_ID
JOIN
  `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.DWH_VI_F_NNV_TVD_12_MONATE` NNA
ON
  VER.DWH_VERTRAG_ID = NNA.DWH_VERTRAG_ID
JOIN
  `{{ var.value.SOURCE_BQ_PROJECT }}.{{ var.value.SOURCE_BQ_DATASET }}.DWH_VI_L_TVD_LEISTUNGSKLASSE` TVD
ON
  NNA.LEISTUNGSKLASSE_ID = TVD.LEISTUNGSKLASSE_ID
WHERE
  NNA.RAHMENVERTRAG IS NOT NULL
  AND NNA.MONATS_ID = CAST('{{ ds_nodash[:6] }}' AS INT64)
  AND TAR.GUELTIG_BIS = PARSE_DATE('%Y%m%d', '47121231')
  AND (
    (TVD.LEISTUNGSKLASSEGR_ID = 1 AND (TVD.LEISTUNGSKLASSE_ID < 300 OR TVD.LEISTUNGSKLASSE_ID > 399))
    OR
    (
      LENGTH(TRIM(CAST(TVD.LEISTUNGSKLASSE_ID AS STRING))) = 6
      AND TVD.LEISTUNGSKLASSE_ID < 699999
      AND TRUNC(CAST(TVD.LEISTUNGSKLASSE_ID AS BIGNUMERIC) / 1000) <> 622
    )
  );