-- Legacy source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_bestandsdaten.sql
-- Job: EXIS
SELECT
    RPT.RAHMENVERTRAG_ID,
    RPT.SV_ID AS TARIF_ID,
    RPT.PARTNER_ID_CARMEN AS T_MOBILE_KUNDENNUMMER,
    RPT.KUNDENKONTO,
    RPT.MSISDN,
    RPT.GEPLANT_KUEND,
    RPT.BINDEFRIST,
    FORMAT_DATE('%d.%m.%Y', DATE(RPT.VERTRAGSBEGINN)) AS VERTRAGSBEGINN,
    RPT.VERTRAGSBINDUNG,
    RPT.DWH_TARIFGR_TEXT,
    STRING_AGG(CAST(A.BPR_ID AS STRING), ',' ORDER BY RPT.RAHMENVERTRAG_ID) AS BASISPRODUKTE
FROM
    `your-gcp-project-id.dwh_raw_layer.RPT$TA_S_D1_VERTRAG` AS RPT
JOIN
    (SELECT
        BPR.CNTRCT_ID,
        BPR.BPR_ID
    FROM
        `your-gcp-project-id.dwh_raw_layer.SOF$TA_BPR_OPTIONEN` AS BPR
    JOIN
        `your-gcp-project-id.dwh_raw_layer.SOF$VI_L_OPTIONZUORDNUNG` AS OPT
    ON
        BPR.BPR_ID = OPT.OPTION_ID
    ) AS A
ON
    RPT.VERTRAG_ID_CARMEN = A.CNTRCT_ID
GROUP BY
    RPT.RAHMENVERTRAG_ID,
    RPT.VERTRAG_ID_CARMEN,
    RPT.SV_ID,
    RPT.PARTNER_ID_CARMEN,
    RPT.KUNDENKONTO,
    RPT.MSISDN,
    RPT.GEPLANT_KUEND,
    RPT.BINDEFRIST,
    RPT.VERTRAGSBEGINN,
    RPT.VERTRAGSBINDUNG,
    RPT.DWH_TARIFGR_TEXT,
    RPT.VERTRAGSSTATUS
ORDER BY
    RPT.VERTRAG_ID_CARMEN;