-- Legacy source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_nna_voice.sql
-- Job: EXIS
SELECT
    NNA.MONATS_ID,
    NNA.RAHMENVERTRAG,
    VER.MSISDN,
    VER.KUNDENKONTO,
    VER.T_MOBILE_KUNDENNUMMER,
    TAR.TARIF_ID,
    CONCAT(TAR.MP_MARKTPRODUKT_BEZ, ',', TAR.MP_EG_JN_BEZ, ',', TAR.MP_GENERATION_BEZ) AS TARIF,
    TVD.LEISTUNGSKLASSE_ID,
    TVD.LEISTUNGSKLASSE_TEXT,
    NNA.VERBINDUNGEN,
    ROUND(CAST(NNA.DAUER_SEK AS NUMERIC) / 60, 2) AS DAUER_MIN,
    ROUND(CAST(NNA.RBETRAG_VBUD_NETTO_CENT AS NUMERIC) / 100, 2) AS RBETRAG_VBUD_NETTO_EURO,
    TAR.MP_EG_JN_ID,
    TAR.MP_EG_JN_BEZ,
    TAR.MP_GENERATION_ID,
    TAR.MP_GENERATION_BEZ
FROM
    (SELECT
        TRF.DWH_TARIF_ID,
        TRF.TARIF_ID,
        D.MP_MARKTPRODUKT_BEZ,
        D.MP_EG_JN_BEZ,
        D.MP_GENERATION_BEZ,
        TRF.GUELTIG_BIS,
        D.MP_EG_JN_ID,
        D.MP_GENERATION_ID
    FROM
        `your-gcp-project-id.dwh_raw_layer.DWH$VI_L_MAP_FA_TARIF` AS TRF
    INNER JOIN
        `your-gcp-project-id.dwh_raw_layer.BL_D_TARIF` AS D
    ON
        TRF.TARIF_ID = D.TARIF_ID
    ) AS TAR
INNER JOIN
    `your-gcp-project-id.dwh_raw_layer.DWH$VI_C_VERTRAG` AS VER
ON
    TAR.DWH_TARIF_ID = VER.DWH_TARIF_ID
INNER JOIN
    `your-gcp-project-id.dwh_raw_layer.DWH$VI_F_NNV_TVD_12_MONATE` AS NNA
ON
    VER.DWH_VERTRAG_ID = NNA.DWH_VERTRAG_ID
INNER JOIN
    `your-gcp-project-id.dwh_raw_layer.DWH$VI_L_TVD_LEISTUNGSKLASSE` AS TVD
ON
    NNA.LEISTUNGSKLASSE_ID = TVD.LEISTUNGSKLASSE_ID
WHERE
    NNA.RAHMENVERTRAG IS NOT NULL
    AND NNA.MONATS_ID = CAST(@FROM_YYYYMM AS INT64)
    AND TAR.GUELTIG_BIS = DATE('4712-12-31')
    AND (
        (TVD.LEISTUNGSKLASSEGR_ID = 1 AND (TVD.LEISTUNGSKLASSE_ID < 300 OR TVD.LEISTUNGSKLASSE_ID > 399))
        OR (
            LENGTH(TRIM(CAST(TVD.LEISTUNGSKLASSE_ID AS STRING))) = 6
            AND TVD.LEISTUNGSKLASSE_ID < 699999
            AND CAST(FLOOR(CAST(TVD.LEISTUNGSKLASSE_ID AS NUMERIC) / 1000) AS INT64) <> 622
        )
    );