-- BigQuery Standard SQL Transformation
-- Legacy Source: vobs/dw_source/isdwh/exporter/apt/sql/d_exis_apt_rabattdaten.sql
-- Job: EXIS_SD_APT_RABATT

-- The BigQuery equivalent of the Oracle SQL query.
-- Oracle-specific hints like /*+ PARALLEL(4)*/ and USE_HASH are removed as BigQuery handles optimization automatically.
-- LISTAGG is replaced with STRING_AGG.
-- Table names are updated to their assumed BigQuery replicated equivalents.

SELECT
    RPT.RAHMENVERTRAG_ID,
    DISC.CNTRCT_TEMPLATE_ID AS TARIF_ID,
    RPT.DWH_TARIFGR_TEXT,
    DISC.RABATTIERTE_RECH_POS,
    DISC.DISC_INVOICE_ITEM_ID AS RABATTIERTE_RECH_POS_ID,
    DISC.RABATTHOEHE,
    STRING_AGG(CAST(BPR.BPR_ID AS STRING), ',') WITHIN GROUP(ORDER BY BPR.BPR_ID) AS BASISPRODUKTE
FROM
    `PROJECT_ID.ORACLE_DATA.RPT_TA_S_D1_VERTRAG` AS RPT
JOIN
    `PROJECT_ID.ORACLE_DATA.RPT_TA_S_D1_DISCOUNT_RR` AS DISC
ON
    RPT.RAHMENVERTRAG_ID = DISC.CONTRACT_NUMBER
    AND RPT.SV_ID = DISC.CNTRCT_TEMPLATE_ID
JOIN
    `PROJECT_ID.ORACLE_DATA.SOF_TA_BPR_OPTIONEN` AS BPR
ON
    RPT.VERTRAG_ID_CARMEN = BPR.CNTRCT_ID
JOIN
    `PROJECT_ID.ORACLE_DATA.SOF_VI_L_OPTIONZUORDNUNG` AS OPT
ON
    BPR.BPR_ID = OPT.OPTION_ID
GROUP BY
    RPT.RAHMENVERTRAG_ID,
    TARIF_ID,
    RPT.DWH_TARIFGR_TEXT,
    DISC.RABATTIERTE_RECH_POS,
    DISC.DISC_INVOICE_ITEM_ID,
    DISC.RABATTHOEHE;