-- BigQuery DDL for carmen_bpd dataset
-- Replaces parts of vobs/dw_source/isrpt/isbert/SQL/aktuell/aufbereitung/bin/r_ausd_rechempf.ksh

CREATE SCHEMA IF NOT EXISTS `carmen_bpd`;

CREATE TABLE IF NOT EXISTS `carmen_bpd.ta_means_of_payment`
(
  BP_ID INT64,
  MEANS_OF_PAYMENT_ID INT64,
  OBJ_VERSION INT64,
  INSERT_AT TIMESTAMP,
  MOP_TY STRING,
  ACCOUNT_INT_BP_ID INT64,
  ACCOUNT_INT_MOP_ID INT64,
  BANK_ID_ACC INT64,
  ACCOUNT_NUMBER_ACC STRING,
  BANK_INTERNATIONAL_ID STRING,
  MANDATE_VAR_CV STRING,
  MANDATE_ST STRING,
  MOP_ST STRING,
  CHECK_ST STRING,
  STATUS_REASON STRING,
  IBAN STRING,
  MANDATE_REFERENCE_NO STRING,
  MANDATE_MIGRATED STRING,
  MANDATE_CITY STRING,
  MANDATE_DATE DATE,
  VALID_FROM DATE,
  VALID_TO DATE,
  INSERT_BY STRING,
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY STRING,
  MODIFY_REASON STRING,
  IS_IN_ARCHIVE BOOL,
  ROW_VERSION INT64,
  REDUNDANT_RB_DOMAIN_PATH STRING,
  REDUNDANT_RB_PROC_PATH STRING,
  IS_PRODUCTION BOOL,
  RB_PARTITION_ID$ INT64
);

CREATE TABLE IF NOT EXISTS `carmen_bpd.ta_bank`
(
  BANK_ID INT64,
  INSERT_AT TIMESTAMP,
  COUNTRY_CODE STRING,
  BANK_SORT_NAME STRING,
  BANK_NAME STRING,
  INSERT_BY STRING,
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY STRING,
  MODIFY_REASON STRING,
  IS_IN_ARCHIVE BOOL,
  ROW_VERSION INT64,
  BIC STRING,
  BANK_INTERNATIONAL_ID STRING
);

CREATE TABLE IF NOT EXISTS `carmen_bpd.ta_bank_international`
(
  INSERT_AT TIMESTAMP,
  COUNTRY_CODE STRING,
  BANK_NAME STRING,
  INSERT_BY STRING,
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY STRING,
  MODIFY_REASON STRING,
  IS_IN_ARCHIVE BOOL,
  ROW_VERSION INT64,
  BIC STRING,
  BANK_INTERNATIONAL_ID STRING
);