-- BigQuery DDL for fos_snapshots dataset
-- Replaces parts of vobs/dw_source/isrpt/isbert/SQL/aktuell/aufbereitung/bin/r_ausd_rechempf.ksh

CREATE SCHEMA IF NOT EXISTS `fos_snapshots`;

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_means_of_pay`
(
  BP_ID INT64,
  MEANS_OF_PAYMENT_ID INT64,
  OBJ_VERSION INT64,
  INSERT_AT TIMESTAMP,
  MOP_TY STRING,
  ACCOUNT_INT_BP_ID INT64,
  ACCOUNT_INT_MOP_ID INT64,
  BANK_ID_ACC INT64,
  ACCOUNT_NUMBER_ACC STRING,
  BANK_INTERNATIONAL_ID STRING,
  MANDATE_VAR_CV STRING,
  MANDATE_ST STRING,
  MOP_ST STRING,
  CHECK_ST STRING,
  STATUS_REASON STRING,
  IBAN STRING,
  MANDATE_REFERENCE_NO STRING,
  MANDATE_MIGRATED STRING,
  MANDATE_CITY STRING,
  MANDATE_DATE DATE,
  VALID_FROM DATE,
  VALID_TO DATE,
  INSERT_BY STRING,
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY STRING,
  MODIFY_REASON STRING,
  IS_IN_ARCHIVE BOOL,
  ROW_VERSION INT64,
  REDUNDANT_RB_DOMAIN_PATH STRING,
  REDUNDANT_RB_PROC_PATH STRING,
  IS_PRODUCTION BOOL,
  RB_PARTITION_ID$ INT64
);

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_bank`
(
  BANK_ID INT64,
  INSERT_AT TIMESTAMP,
  COUNTRY_CODE STRING,
  BANK_SORT_NAME STRING,
  BANK_NAME STRING,
  INSERT_BY STRING,
  MODIFIED_AT TIMESTAMP,
  MODIFIED_BY STRING,
  MODIFY_REASON STRING,
  IS_IN_ARCHIVE BOOL,
  ROW_VERSION INT64,
  BIC STRING,
  BANK_INTERNATIONAL_ID STRING
);

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_bank_verb`
(
  MEANS_OF_PAYMENT_ID INT64,
  BP_ID INT64,
  ACCOUNT_NUMBER_ACC STRING,
  BANK_NAME STRING,
  BANK_SORT_NAME STRING,
  IBAN STRING,
  BIC STRING
);

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_bank_zuord`
(
  INV_DEF_MOPREF_ID INT64,
  ACCOUNT_NUMBER_ACC STRING,
  BANK_NAME STRING,
  BANK_SORT_NAME STRING,
  IBAN STRING,
  BIC STRING
);

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_p_rech_empf`
(
  KUNDENKONTO STRING,
  RECHDEF_ID INT64,
  DPPS_KONTONUMMER STRING,
  RECHNUNGSEMPFAENGER STRING,
  QUELLE STRING,
  AKAD_TITEL STRING,
  FIRMA STRING,
  VORNAME STRING,
  NACHNAME STRING,
  ZUSATZ_1 STRING,
  ZUSATZ_2 STRING,
  STRASSE STRING,
  PLZ STRING,
  WOHNORT STRING,
  LAND STRING,
  BANKNAME STRING,
  BANK_KONTONUMMER STRING,
  BLZ STRING,
  ORGANISATIONSEINHEIT STRING,
  MWST_KENNZEICHEN BOOL,
  KUN_NR_RECH_EMPF STRING,
  IBAN STRING,
  BIC STRING
);

CREATE TABLE IF NOT EXISTS `fos_snapshots.sof_ta_p_d1_vpn`
(
  VERTRAGS_ID INT64,
  VPN_ID INT64
);